services:
  clickhouse-server:
    container_name: clickhouse-server
    image: clickhouse/clickhouse-server:24.4
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./config/single_node_cluster.xml:/etc/clickhouse-server/config.d/98_single_node_cluster.xml:ro
volumes:
  ch_data:
